### ISSUE TITLE
Fabber widget returning error when opened

### ISSUE THREAD

**Issue by thomasbeaudry** [ibme-qubic/quantiphyse-fabber#4]
Hi,

I added the fabber widget to Quantiphyse but when i click on it I get thte following error:

Value poly is not a valid choice for this option

Details:

Traceback (most recent call last):

File "/NAS/home/perform-admin/.conda/envs/qp/lib/python2.7/site-packages/quantiphyse/gui/MainWindow.py", line 214, in _show_widget
w.init_ui()

File "/NAS/home/perform-admin/.conda/envs/qp/lib/python2.7/site-packages/quantiphyse_fabber/widget.py", line 194, in init_ui
self.options.option("model").value = "poly"

File "/NAS/home/perform-admin/.conda/envs/qp/lib/python2.7/site-packages/quantiphyse/gui/options.py", line 493, in value
raise ValueError("Value %s is not a valid choice for this option" % choice)

ValueError: Value poly is not a valid choice for this option

What do i need to install / load before being able to use this widget?  FSL is already loaded before i open Quantiphyse.  thanks!

**Comment by mcraig-ibme** [comment]
Hi, what version of FSL do you have? You need FSL 6.0.1 or later, or if this is not possible you'd need to install the 'fabber bundle' containing more recent fabber code:

https://github.com/ibme-qubic/fabber_core/releases/tag/v4.0.6

**Comment by mcraig-ibme** [comment]
Closing - most likely FSL version not sufficient.
